"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WISE_NORTH_EAST = exports.WISE_NORTH = exports.WISE_NORTH_WEST = exports.WISE_WEST = exports.WISE_SOUTH_WEST = exports.WISE_SOUTH = exports.WISE_SOUTH_EAST = exports.WISE_EAST = exports.NORTH_EAST = exports.NORTH = exports.NORTH_WEST = exports.WEST = exports.SOUTH_WEST = exports.SOUTH = exports.SOUTH_EAST = exports.EAST = void 0;
exports.EAST = "E";
exports.SOUTH_EAST = "SE";
exports.SOUTH = "S";
exports.SOUTH_WEST = "SW";
exports.WEST = "W";
exports.NORTH_WEST = "NW";
exports.NORTH = "N";
exports.NORTH_EAST = "NE";
exports.WISE_EAST = "Wise E";
exports.WISE_SOUTH_EAST = "Wise SE";
exports.WISE_SOUTH = "Wise S";
exports.WISE_SOUTH_WEST = "Wise SW";
exports.WISE_WEST = "Wise W";
exports.WISE_NORTH_WEST = "Wise NW";
exports.WISE_NORTH = "Wise N";
exports.WISE_NORTH_EAST = "Wise NE";
//# sourceMappingURL=direction.js.map