"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.typeDisk = exports.colorDisk = exports.swatchDisk = exports.existDisk = exports.deleteDisk = exports.ensureDisk = exports.trashDisk = exports.batchDisk = exports.frameDisk = exports.copyDisk = exports.load_listDisk = exports.indexDisk = exports.readDisk = exports.writeDisk = exports.updateDisk = exports.initDisk = void 0;
var disk_buzz_1 = require("./buz/disk.buzz");
Object.defineProperty(exports, "initDisk", { enumerable: true, get: function () { return disk_buzz_1.initDisk; } });
var disk_buzz_2 = require("./buz/disk.buzz");
Object.defineProperty(exports, "updateDisk", { enumerable: true, get: function () { return disk_buzz_2.updateDisk; } });
var disk_buzz_3 = require("./buz/disk.buzz");
Object.defineProperty(exports, "writeDisk", { enumerable: true, get: function () { return disk_buzz_3.writeDisk; } });
var disk_buzz_4 = require("./buz/disk.buzz");
Object.defineProperty(exports, "readDisk", { enumerable: true, get: function () { return disk_buzz_4.readDisk; } });
var disk_buzz_5 = require("./buz/disk.buzz");
Object.defineProperty(exports, "indexDisk", { enumerable: true, get: function () { return disk_buzz_5.indexDisk; } });
var disk_buzz_6 = require("./buz/disk.buzz");
Object.defineProperty(exports, "load_listDisk", { enumerable: true, get: function () { return disk_buzz_6.load_listDisk; } });
var disk_buzz_7 = require("./buz/disk.buzz");
Object.defineProperty(exports, "copyDisk", { enumerable: true, get: function () { return disk_buzz_7.copyDisk; } });
var disk_buzz_8 = require("./buz/disk.buzz");
Object.defineProperty(exports, "frameDisk", { enumerable: true, get: function () { return disk_buzz_8.frameDisk; } });
var disk_buzz_9 = require("./buz/disk.buzz");
Object.defineProperty(exports, "batchDisk", { enumerable: true, get: function () { return disk_buzz_9.batchDisk; } });
var disk_buzz_10 = require("./buz/disk.buzz");
Object.defineProperty(exports, "trashDisk", { enumerable: true, get: function () { return disk_buzz_10.trashDisk; } });
var disk_buzz_11 = require("./buz/disk.buzz");
Object.defineProperty(exports, "ensureDisk", { enumerable: true, get: function () { return disk_buzz_11.ensureDisk; } });
var disk_buzz_12 = require("./buz/disk.buzz");
Object.defineProperty(exports, "deleteDisk", { enumerable: true, get: function () { return disk_buzz_12.deleteDisk; } });
var disk_buzz_13 = require("./buz/disk.buzz");
Object.defineProperty(exports, "existDisk", { enumerable: true, get: function () { return disk_buzz_13.existDisk; } });
var disk_buzz_14 = require("./buz/disk.buzz");
Object.defineProperty(exports, "swatchDisk", { enumerable: true, get: function () { return disk_buzz_14.swatchDisk; } });
var disk_buzz_15 = require("./buz/disk.buzz");
Object.defineProperty(exports, "colorDisk", { enumerable: true, get: function () { return disk_buzz_15.colorDisk; } });
var disk_buzz_16 = require("./buz/disk.buzz");
Object.defineProperty(exports, "typeDisk", { enumerable: true, get: function () { return disk_buzz_16.typeDisk; } });
//# sourceMappingURL=disk.buzzer.js.map